#!/bin/sh

target=$1
echo "Downgrading $target to c++14."
for srcfile in $target/src/*.{cpp,h} $target/src/**/*.{cpp,h}; do
  echo "  → $srcfile"
  nvim -Es $srcfile -S ./downgrade.namespaces.vim
done
echo "Downgrading Makefile CC_FLAGS."
nvim -Es $target/Makefile -S ./downgrade.Makefile.vim
echo "Running Makefile to ensure nothing breaks."
cd $target
make clean all
